### PR TITLE
Fix: Add text-overflow

### LINKED ISSUE #203: Contributor's name is overflowing in the leaderboard
**Description**

When the contributor has a lengthy name like "Konavivekramakrishna" , the text overflows in the leaderboard

**Screenshot of the bug**

image

### PR DESCRIPTION
**Pull request by corners2wall**
Closes #203 

Added `text-overflow` 

Screenshot from 2024-01-19 13-42-12

### CODE REVIEW

File: components/contributors/InfoCard.tsx [hunk 1]
```diff
@@ -38,15 +38,22 @@ export default function InfoCard({
...
-        <div className={minimal ? "" : "flex flex-col items-center space-y-2"}>
-          <div className="font-medium text-lg space-y-1">
+        <div
+          className={`overflow-hidden ${
+            minimal
+              ? ""
+              : "flex flex-col items-center space-y-2 overflow-hidden"
+          }
+          `}
+        >
```
Comment (rithviknishad) [inline components/contributors/InfoCard.tsx:48]: We are having "overflow-hidden" class applied multiple times if `minimal=true`

**Review by rithviknishad — CHANGES_REQUESTED** [review]
LGTM, just a minor cleanup

File: components/contributors/InfoCard.tsx (hunk 1 above)
Comment (corners2wall) [reply components/contributors/InfoCard.tsx]: Sorry, mistake. Changed

**Review by rithviknishad — APPROVED** [review]
Nice work, LGTM
